<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function myFindAll()
    {
        return $this->createQueryBuilder('a')
            ->getQuery()
            ->getResult();
    }


    /**
     * @param $id
     * @return array
     */
    public function myFindOne($id)
    {
        return $this->createQueryBuilder('a')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult()
            ;
    }

    /**
     * @param $pattern
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getLikeQueryBuilder($pattern) {
        //Cette méthode retourne un queryBuilder et non une query
        return $this->createQueryBuilder('c')
            ->where('c.name LIKE :pattern')
            ->setParameter('pattern', $pattern)
            ;
    }
}
