<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {

        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email OR u.apiKey = :apiKey')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->setParameter('apiKey', $username)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
