imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    position: bottom
    intercept_redirects: true

monolog:
    handlers:
        syslog:
            type: stream
            path: /tmp/symfony.log
            level: ERROR
            channels: [!event]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    delivery_address: fabien@gvmail.com
    delivery_whitelist:
        - '/^fabien-ovs@gvmail\.fr$/'
    spool: {type: memory}
debug:
    max_items: 2500
    max_string_length: -1
    #dump_destination: /tmp/error.txt


