app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/
    requirements:
        _locale: fr|en

logout:
    path: /logout

coresphere_console:
    resource: .
    type: extra
