# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - {name: twig.extension}
    app.image_type_extension:
        class: AppBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type.extension, extended_type:Symfony\Component\Form\Extension\Core\Type\FileType}
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
    app.switch_user_listener:
        class: AppBundle\EventListener\SwitchUserListener
        tags:
            - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser}
    app.webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
#    app.api_key_user_provider:
#        class: AppBundle\Security\ApiKeyUserProvider;
#    app.apikey_authenticator:
#        class: AppBundle\Security\ApiKeyAuthenticator
#        public: false
#    security.exception_listener:
#        class: AppBundle\Security\Firewall\ExceptionListener

