jQuery(document).ready(function() {

    var morse=new Array(36);
    morse[1]=". -";
    morse[2]="- . . .";
    morse[3]="- . - .";
    morse[4]="- . .";
    morse[5]=".";
    morse[6]=". . - .";
    morse[7]="- - .";
    morse[8]=". . . .";
    morse[9]=". .";
    morse[10]=". - - -";
    morse[11]="- . -";
    morse[12]=". - . .";
    morse[13]="- -";
    morse[14]="- .";
    morse[15]="- - -";
    morse[16]=". - - .";
    morse[17]="- - . -";
    morse[18]=". - .";
    morse[19]=". . .";
    morse[20]="-";
    morse[21]=". . -";
    morse[22]=". . . -";
    morse[23]=". - -";
    morse[24]="- . . -";
    morse[25]="- . - -";
    morse[26]="- - . .";
    morse[27]=". - - - -";
    morse[28]=". . - - -";
    morse[29]=". . . - -";
    morse[30]=". . . . -";
    morse[31]=". . . . .";
    morse[32]="- . . . .";
    morse[33]="- - . . .";
    morse[34]="- - - . .";
    morse[35]="- - - - .";
    morse[36]="- - - - -";

var verif=new Array(36);
    verif[1]="a";
    verif[2]="b";
    verif[3]="c";
    verif[4]="d";
    verif[5]="e";
    verif[6]="f";
    verif[7]="g";
    verif[8]="h";
    verif[9]="i";
    verif[10]="j";
    verif[11]="k";
    verif[12]="l";
    verif[13]="m";
    verif[14]="n";
    verif[15]="o";
    verif[16]="p";
    verif[17]="q";
    verif[18]="r";
    verif[19]="s";
    verif[20]="t";
    verif[21]="u";
    verif[22]="v";
    verif[23]="w";
    verif[24]="x";
    verif[25]="y";
    verif[26]="z";
    verif[27]="1";
    verif[28]="2";
    verif[29]="3";
    verif[30]="4";
    verif[31]="5";
    verif[32]="6";
    verif[33]="7";
    verif[34]="8";
    verif[35]="9";
    verif[36]="0";

    $("form_submit").on('click', function() {
        elem = 0;
    	attendre = 0;
    	touche = 0;
    	droitpresser = false;
    	questionsf = 0;
    	note = 0;

        var secondes = Math.max(1, parseInt($("#form_time").val()));
        var questions = Math.max(1, parseInt($("#form_questions").val()));
        jQuery('#morse').html('');
        jQuery("#responses").html('');
        window.clearTimeout(toid);
        Nouveau();
    });
});
